# -*- coding: utf-8 -*-
#
# =============================================================================
# HOW TO BUILD THE DOCUMENTATION
# =============================================================================
#
# The docs are generated by Sphinx using sphinx.ext.autodoc, which imports
# pysimplelog at build time and extracts every docstring from SimpleLog.py
# automatically.  No manual copy-pasting is needed: editing a docstring in
# the source and rebuilding is all it takes to update the rendered output.
#
# -- One-time setup -----------------------------------------------------------
#
#   Sphinx cannot be installed into the active Python environment if it is
#   managed by another tool.  Create a dedicated virtual environment for the
#   docs instead (run these commands from the repo root, not from docs/):
#
#       uv venv .sphinx-venv --python 3.13
#       uv pip install sphinx --python .sphinx-venv/bin/python3
#
#   The alabaster theme ships bundled with Sphinx -- no extra package needed.
#
# -- Building -----------------------------------------------------------------
#
#   All build commands must be run from inside the docs/ directory:
#
#       cd docs
#
#   Build the HTML documentation, pointing make at the venv's sphinx-build:
#
#       make html SPHINXBUILD="../.sphinx-venv/bin/sphinx-build"
#
#   The output lands in docs/build/html/.  Open the entry point with:
#
#       open build/html/index.html          # macOS
#       xdg-open build/html/index.html      # Linux
#
#   Other useful targets (all accept the same SPHINXBUILD override):
#
#       make clean      -- wipe docs/build/ entirely for a fresh build
#       make singlehtml -- produce one large HTML file instead of many
#       make text       -- plain-text output, useful for grepping the docs
#       make linkcheck  -- verify all external URLs in the docs are alive
#
# -- Everyday workflow --------------------------------------------------------
#
#   After any docstring change in SimpleLog.py, a full rebuild is just:
#
#       cd docs && make html SPHINXBUILD="../.sphinx-venv/bin/sphinx-build"
#
#   To avoid typing the SPHINXBUILD override every time, edit the one line
#   in docs/Makefile:
#
#       SPHINXBUILD = ../.sphinx-venv/bin/sphinx-build
#
#   After that change, plain `make html` works with no extra arguments.
#
# -- Troubleshooting ----------------------------------------------------------
#
#   "make: sphinx-build: No such file or directory"
#       The SPHINXBUILD variable is pointing at the wrong binary.
#       Always pass the full path:
#           make html SPHINXBUILD="../.sphinx-venv/bin/sphinx-build"
#
#   "ModuleNotFoundError: No module named 'sphinx'"
#       Sphinx is not installed in the active venv.  Re-run the setup step.
#
#   "ModuleNotFoundError: No module named 'pysimplelog'"
#       The package is not importable from the venv's Python.  conf.py
#       already inserts the repo root onto sys.path, so this usually means
#       the venv was created from a different Python installation.
#       Recreate it with:  uv venv .sphinx-venv --python 3.13
#
#   "WARNING: autodoc: failed to import module 'pysimplelog.SimpleLog'"
#       There is a syntax error in SimpleLog.py.  Check it with:
#           python3 -c "import ast; ast.parse(open('SimpleLog.py').read())"
#
#   "WARNING: Title underline too short"
#       An RST heading in a docstring has a mismatched underline length.
#       Look at the file and line number printed by Sphinx to locate it.
#
# =============================================================================
#
# pysimplelog documentation build configuration file, created by
# sphinx-quickstart on Mon Sep 12 22:54:29 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.

import os
import sys
import datetime

# -- Path setup ---------------------------------------------------------------
# Make the pysimplelog package importable from docs/source by inserting the
# repo root (two levels up from this file) onto sys.path.
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'

# General information about the project.
project = u'pysimplelog'
copyright = u'2016\u2013%d, Bachir Aoun' % datetime.date.today().year
author = u'Bachir Aoun'

# Version
try:
    from pysimplelog import __version__ as VER
    from pysimplelog import SimpleLog
    if SimpleLog.__doc__:
        SimpleLog.__doc__ = SimpleLog.__doc__.replace("%AUTO_VERSION", VER)
except Exception as _e:
    print(
        "pysimplelog import failed during doc build: %s" % _e,
        file=sys.stderr,
    )
    VER = "unknown"

version = VER
release = VER

rst_epilog = """
.. |VERSION| replace:: %s
""" % (VER,)

language = 'en'
exclude_patterns = []
pygments_style = 'sphinx'
todo_include_todos = False
autodoc_member_order = 'bysource'

# -- Options for HTML output ----------------------------------------------

html_theme = 'alabaster'
html_theme_options = {
    'github_user': "bachiraoun",
    'github_repo': "pysimplelog",
    'github_banner': True,
    'show_powered_by': False,
}

html_title = u'pysimplelog v%s' % VER
html_short_title = html_title
project_name = html_title

html_static_path = ['_static']

html_sidebars = {
    '**': ['about.html', 'navigation.html', 'searchbox.html'],
}

html_show_sourcelink = False
html_show_sphinx = False
html_show_copyright = True

htmlhelp_basename = 'pysimplelogdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}
latex_documents = [
    (master_doc, 'pysimplelog.tex', u'pysimplelog Documentation',
     u'Bachir Aoun', 'manual'),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'pysimplelog', u'pysimplelog Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, 'pysimplelog', u'pysimplelog Documentation',
     author, 'pysimplelog',
     'A complete logging system with enqueue, bind(), catch(), and multi-sink routing.',
     'Miscellaneous'),
]
